apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kodekamp-db-data
  namespace: kodekamp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
