apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitchdropsminer
  namespace: twitchdropsminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitchdropsminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: twitchdropsminer
    spec:
      containers:
        - env:
            - name: DARK_MODE
              value: "1"
            - name: TZ
              value: Europe/Oslo
          image: docker.io/dungfu/twitch-drops-miner:latest@sha256:33bcbfd42fcfe116b1e6af0133796ba159b017eb5e2c61d84e8fec81a56d2174
          name: twitchdropsminer
          ports:
            - containerPort: 5800
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
          volumeMounts:
            - mountPath: /TwitchDropsMiner/cache
              name: cache
            - mountPath: /TwitchDropsMiner/config
              name: config
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: twitchdropsminer-cache
        - name: config
          persistentVolumeClaim:
            claimName: twitchdropsminer-config
