apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/backup: enabled
    recurring-job-group.longhorn.io/snapshot: enabled
    recurring-job.longhorn.io/source: enabled
  name: twitchdropsminer-config
  namespace: twitchdropsminer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
