apiVersion: v1
data:
  config.yml: |
    ntfy:
      baseurl: http://ntfy.ntfy.svc.cluster.local
      notification:
        topic: alerts
        priority: |
          status == "firing" ? "high" : "default"
        tags:
          - tag: rotating_light
            condition: status == "firing"
          - tag: white_check_mark
            condition: status == "resolved"
        templates:
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
          description: |
            {{ index .Annotations "description" }}
kind: ConfigMap
metadata:
  name: alertmanager-ntfy
  namespace: victoria-metrics
