apiVersion: v1
data:
  datasource.yaml: "apiVersion: 1\ndatasources: \n  - access: proxy\n    isDefault: true\n    name: VictoriaMetrics\n    type: prometheus\n    uid: VictoriaMetrics\n    url: http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8428\n  - access: proxy\n    isDefault: false\n    name: VictoriaMetrics (DS)\n    type: victoriametrics-metrics-datasource\n    uid: VictoriaMetricsDS\n    url: http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8428\n  - access: proxy\n    name: VictoriaLogs (DS)\n    type: victoriametrics-logs-datasource\n    uid: VictoriaLogs\n    url: http://vlsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:9428\n  - access: proxy\n    jsonData:\n      handleGrafanaManagedAlerts: true\n      implementation: prometheus\n    name: Alertmanager\n    type: alertmanager\n    uid: Alertmanager\n    url: http://vmalertmanager-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:9093"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.150.0
    grafana_datasource: "1"
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.2
  name: vm-victoria-metrics-k8s-stack-grafana-ds
  namespace: victoria-metrics
