apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: vm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 13.2.0
    helm.sh/chart: grafana-12.7.3
  name: vm-grafana
  namespace: victoria-metrics
