apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: grafana
    tailscale.com/proxy-group: ingress
  name: grafana-tailscale
  namespace: victoria-metrics
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: vm
    app.kubernetes.io/name: grafana
  type: LoadBalancer
