apiVersion: operator.victoriametrics.com/v1
kind: VLAgent
metadata:
  labels:
    app.kubernetes.io/component: vlagent
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.52.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.2
  name: vm-victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  image:
    tag: v1.52.0
  k8sCollector:
    enabled: true
  port: "9429"
  remoteWrite:
    - url: http://vlsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:9428/insert/native
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
