apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  labels:
    app.kubernetes.io/component: vlsingle
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.52.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.2
  name: vm-victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  extraArgs:
    retention.maxDiskSpaceUsageBytes: 8GiB
    vmalert.proxyURL: http://vmalert-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8080
  image:
    tag: v1.52.0
  port: "9428"
  replicaCount: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  retentionPeriod: 30d
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: longhorn
