apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v0.32.1
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.0
  name: vm-victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  configSecret: vmalertmanager-vm-victoria-metrics-k8s-stack
  externalURL: ""
  image:
    tag: v0.32.1
  port: "9093"
  replicaCount: 1
  routePrefix: /
  selectAllByDefault: true
  templates:
    - key: monzo.tmpl
      name: vmalertmanager-vm-victoria-metrics-k8s-stack-monzo-tpl
