apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  labels:
    app.kubernetes.io/component: vmalert
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.150.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.2
  name: vm-victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  configMaps: []
  datasource:
    url: http://vmauth-vm-victoria-metrics-k8s-stack-internal.victoria-metrics.svc.cluster.local.:8427
  evaluationInterval: 20s
  externalLabels: {}
  extraArgs:
    external.alert.source: explore?left={"datasource":"VictoriaMetrics","queries":[{"expr":{{ .Expr|jsonEscape|queryEscape }},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}
    external.url: http://
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    tag: v1.150.0@sha256:c6e6c1ef6e43c09510dd0aff264bf0ea319c1bdfced1ccc79dad1545950a7989
  notifiers:
    - url: http://vmalertmanager-vm-victoria-metrics-k8s-stack-0.vmalertmanager-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:9093
  port: "8080"
  remoteRead:
    url: http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8428
  remoteWrite:
    url: http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8428/api/v1/write
  selectAllByDefault: true
