apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  labels:
    app.kubernetes.io/component: vmauth
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.151.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.91.2
  name: vm-victoria-metrics-k8s-stack-internal
  namespace: victoria-metrics
spec:
  image:
    tag: v1.151.0@sha256:efd05bb90de99c842dae9b5848a0c83347caf5004c3e81deabcc8562024ab072
  port: "8427"
  unauthorizedUserAccessSpec:
    url_map:
      - src_paths:
          - /select/logsql/.*
        url_prefix:
          - http://vlsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:9428/
      - src_paths:
          - /.*
        url_prefix:
          - http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics.svc.cluster.local.:8428/
