apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-redis
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless-redis
    spec:
      containers:
        - command:
            - redis-server
          image: redis:8.10-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-redis-data
