apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  namespace: paperless-ngx
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: paperless-redis
