apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  namespace: changedetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: BASE_URL
              value: http://changedetection.tail84b6c.ts.net
            - name: DEFAULT_FETCH_BACKEND
              value: html_cloakbrowser
            - name: FETCH_WORKERS
              value: "3"
            - name: HOME
              value: /tmp
            - name: TZ
              value: Europe/Oslo
          image: registry.tail84b6c.ts.net/changedetection:0.55.8-2029456b
          name: changedetection
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /datastore
              name: data
            - mountPath: /dev/shm
              name: dshm
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: changedetection-data
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: dshm
