apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-public-proxy
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-public-proxy
  template:
    metadata:
      labels:
        app: immich-public-proxy
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: IMMICH_URL
              value: http://immich-server:2283
          image: ghcr.io/alangrainger/immich-public-proxy:3.4.0@sha256:b442829bb99e25f39e2979bb45bb12a6db991d98a1cd90938799b84ab262692a
          name: proxy
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
