apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-public-proxy
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-public-proxy
  template:
    metadata:
      labels:
        app: immich-public-proxy
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: IMMICH_URL
              value: http://immich-server:2283
          image: ghcr.io/alangrainger/immich-public-proxy:3.3.1@sha256:8657d0d1b79e7f008261bbb65c2f177a89e8a0fd325b9a312d16cf7b5cbee209
          name: proxy
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
