apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    tailscale.com/funnel: "true"
  name: immich-funnel
  namespace: immich
spec:
  defaultBackend:
    service:
      name: immich-public-proxy
      port:
        number: 3000
  ingressClassName: tailscale
  tls:
    - hosts:
        - immich-share
