apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: immich-server
  namespace: immich
spec:
  endpoints:
    - port: metrics-api
    - port: metrics-ms
  selector:
    matchLabels:
      app.kubernetes.io/service: immich-server
