apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Oslo
          image: docker.io/jvmilazz0/kavita:0.9.0@sha256:36aab0c578d488f8b10bd33910953b50965aff9ac6adc476ef4692c38c60427e
          name: kavita
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /kavita/config
              name: config
            - mountPath: /library
              name: library
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: kavita-config
        - name: library
          persistentVolumeClaim:
            claimName: kavita-library
