apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/backup: enabled
    recurring-job-group.longhorn.io/snapshot: enabled
    recurring-job.longhorn.io/source: enabled
  name: kavita-config
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
