apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
    homelab.teevik.dev/image-builds: '[{"context":"/workspace","image":"amp","tag":"v28-04765fa7"}]'
  name: build-amp
  namespace: amp
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: build-amp
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - sh
            - -c
            - |+
              set -eu
              if wget -q --spider --header "Accept: application/vnd.oci.image.index.v1+json, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json" "http://zot.registry.svc:5000/v2/amp/manifests/v28-04765fa7"; then
                echo "zot.registry.svc:5000/amp:v28-04765fa7 is already in the registry; skipping build"
              else
                echo "building zot.registry.svc:5000/amp:v28-04765fa7"
                buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=/workspace --local dockerfile=/workspace \
                  --output type=image,name=zot.registry.svc:5000/amp:v28-04765fa7,push=true,registry.insecure=true \
                  --export-cache type=registry,ref=zot.registry.svc:5000/amp:buildcache,mode=max,registry.insecure=true \
                  --import-cache type=registry,ref=zot.registry.svc:5000/amp:buildcache,registry.insecure=true
              fi

          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
            - name: DOCKER_CONFIG
              value: /home/user/.docker
          image: docker.io/moby/buildkit:v0.32.2-rootless@sha256:504731e577c20559c00f968f33219f30115e70be29ab96728d1d06e963fc494b
          name: buildkit
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          securityContext:
            appArmorProfile:
              type: Unconfined
            runAsGroup: 1000
            runAsUser: 1000
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - mountPath: /home/user/.docker
              name: docker-config
              readOnly: true
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
            - mountPath: /workspace
              name: workspace
              readOnly: true
      restartPolicy: Never
      volumes:
        - emptyDir: {}
          name: buildkitd
        - name: docker-config
          secret:
            secretName: amp-registry-push
        - configMap:
            name: amp-build-context
          name: workspace
