apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      annotations:
        checksum/config: 4d0d29f9098b842b84be77b2c2f97552ff1cda1364c5472e3af9b0b4f1e74050
      labels:
        app: glance
    spec:
      containers:
        - image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
          name: glance
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /app/config/glance.yml
              name: config
              subPath: glance.yml
      volumes:
        - configMap:
            name: glance-config
          name: config
