apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      annotations:
        checksum/config: 962b60184ad42aa2556739eccdb706793e5febdb0545b24de4324b00e912e7a6
      labels:
        app: glance
    spec:
      containers:
        - image: glanceapp/glance:v0.8.5@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
          name: glance
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /app/config/glance.yml
              name: config
              subPath: glance.yml
      volumes:
        - configMap:
            name: glance-config
          name: config
