apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: glance
    tailscale.com/proxy-group: ingress
  name: glance
  namespace: glance
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: glance
  type: LoadBalancer
