apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: ntfy
    tailscale.com/proxy-group: ingress
  name: ntfy-tailscale
  namespace: ntfy
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: ntfy
  type: LoadBalancer
