apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: argocd
    tailscale.com/proxy-group: ingress
  name: argocd-tailscale
  namespace: argocd
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
