apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: reclip
    tailscale.com/proxy-group: ingress
  name: reclip-tailscale
  namespace: reclip
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8899
  selector:
    app: reclip
  type: LoadBalancer
