//! Input contracts: what the renderer reads, and nothing else.
//!
//! Three JSON documents, each written atomically (write, then rename) by its owner:
//!
//! - [`Catalog`]: generated by Nix from the service catalog at build time.
//! - [`Snapshot`]: written by the host collector, normalised and timestamped.
//! - [`NightReport`]: written by the night-policy controller.
//!
//! The renderer never evaluates Nix, loads a kubeconfig, receives credentials or
//! controls device power. Every time here is an actual observation time, not the
//! time a query returned; freshness is derived from them at an explicit `now`.
//! `docs/health-dashboard.md` documents the same contracts with examples.

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Every document carries `"version": 1`. A different version is rejected, not guessed at.
pub const VERSION: u32 = 1;

// ---------------------------------------------------------------- catalog

/// Generated from the service catalog. Order is presentation order and never changes
/// with health.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Catalog {
    pub version: u32,
    pub endpoints: Vec<CatalogEndpoint>,
    /// Expected Argo CD apps, including infrastructure without an endpoint. Derived
    /// separately from the endpoints: endpoints do not define the app inventory.
    pub apps: Vec<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct CatalogEndpoint {
    /// Stable service identity, the key of [`Snapshot::endpoints`].
    pub id: String,
    /// Human name shown in the ledger.
    pub name: String,
    /// The Argo CD app this endpoint belongs to. Several endpoints may share one app;
    /// `None` is a host-only endpoint.
    #[serde(default)]
    pub app: Option<String>,
}

// ---------------------------------------------------------------- snapshot

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Snapshot {
    pub version: u32,
    pub collector_started_at: Timestamp,
    pub sources: Sources,
    #[serde(default)]
    pub host: Host,
    /// Latest HTTP check per catalog endpoint id. An expected id that is absent is a
    /// coverage gap once the HTTP source is current.
    #[serde(default)]
    pub endpoints: BTreeMap<String, EndpointResult>,
    /// Latest Argo CD report per app id.
    #[serde(default)]
    pub apps: BTreeMap<String, AppResult>,
    /// Unhealthy or unready workloads and one-hour restarts.
    #[serde(default)]
    pub workloads: Vec<WorkloadSignal>,
    /// Active, unsilenced, uninhibited alerts (Watchdog/InfoInhibitor excluded).
    #[serde(default)]
    pub alerts: Vec<AlertSignal>,
    /// Services whose signals affirmatively cleared. The collector owns retention; the
    /// renderer shows at most three cleared less than 15 minutes ago.
    #[serde(default)]
    pub recoveries: Vec<Recovery>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Sources {
    pub host: SourceReport,
    pub http: SourceReport,
    pub argo: SourceReport,
    pub alerts: SourceReport,
}

/// One collector input. Waiting before its first observation, current while its
/// newest underlying sample is at most 3 minutes old, stale after that, and
/// unavailable whenever its latest refresh failed.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Default)]
pub struct SourceReport {
    /// Time of the newest underlying sample (not the query receipt time).
    #[serde(default)]
    pub newest_sample_at: Option<Timestamp>,
    /// Set while the latest refresh failed; cleared by the next valid one.
    #[serde(default)]
    pub failure: Option<Failure>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Failure {
    pub since: Timestamp,
    /// One short sentence, e.g. "cluster API rejected the collector credential (HTTP 401)".
    pub reason: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct EndpointResult {
    /// Time of this target's own sample.
    pub observed_at: Timestamp,
    #[serde(flatten)]
    pub check: Check,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "result", rename_all = "lowercase")]
pub enum Check {
    Ok {
        latency_ms: u32,
    },
    Fail {
        /// Short failure text, e.g. "HTTP 503" or "timeout 3.0s".
        reason: String,
        /// When this failure was first observed.
        since: Timestamp,
    },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct AppResult {
    pub observed_at: Timestamp,
    /// Argo CD sync status; anything other than `Synced` is a signal.
    pub sync: String,
    #[serde(default)]
    pub sync_since: Option<Timestamp>,
    /// Argo CD health status; anything other than `Healthy` is a signal.
    pub health: String,
    #[serde(default)]
    pub health_since: Option<Timestamp>,
}

impl AppResult {
    pub fn is_synced(&self) -> bool {
        self.sync == "Synced"
    }

    pub fn is_healthy(&self) -> bool {
        self.health == "Healthy"
    }

    /// Degraded stays red wherever it appears.
    pub fn is_degraded(&self) -> bool {
        self.health == "Degraded"
    }
}

/// Evidence that matched a catalog app through trustworthy labels/ownership, or else
/// kept under its own label (for example "cluster") rather than dropped.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct WorkloadSignal {
    #[serde(default)]
    pub app: Option<String>,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(flatten)]
    pub problem: WorkloadProblem,
    pub since: Timestamp,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "problem", rename_all = "lowercase")]
pub enum WorkloadProblem {
    /// Container restarts over the last hour.
    Restarts { count: u32 },
    /// Workloads that are not ready.
    Unready { count: u32 },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct AlertSignal {
    pub name: String,
    #[serde(default)]
    pub app: Option<String>,
    #[serde(default)]
    pub label: Option<String>,
    pub since: Timestamp,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Recovery {
    /// Endpoint id, app id or evidence label of the recovered service.
    pub service: String,
    /// The last problem, e.g. "HTTP 503".
    pub problem: String,
    pub began_at: Timestamp,
    pub cleared_at: Timestamp,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Default)]
pub struct Host {
    /// `None` until a second CPU sample exists.
    #[serde(default)]
    pub cpu_percent: Option<f32>,
    #[serde(default)]
    pub cpu_threads: Option<u32>,
    /// Available versus total memory.
    #[serde(default)]
    pub memory: Option<Capacity>,
    /// Host-root filesystem: available versus total capacity.
    #[serde(default)]
    pub root: Option<Capacity>,
    #[serde(default)]
    pub temperature: Temperature,
    #[serde(default)]
    pub temperature_history: TemperatureHistory,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
pub struct Capacity {
    pub total_bytes: u64,
    pub available_bytes: u64,
}

/// Optional CPU/package sensor. Its absence never affects the status.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Default)]
#[serde(tag = "state", rename_all = "lowercase")]
pub enum Temperature {
    #[default]
    Waiting,
    Reading {
        celsius: f32,
        /// Sensor label, e.g. "Tctl".
        sensor: String,
    },
    /// No verified CPU/package sensor exists.
    Unavailable,
}

/// One value per minute from real samples, oldest first, ending at `end`. `null` is a
/// minute without a sample. Starts empty; bounded by the collector.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Default)]
pub struct TemperatureHistory {
    #[serde(default)]
    pub end: Option<Timestamp>,
    #[serde(default)]
    pub celsius: Vec<Option<f32>>,
}

// ---------------------------------------------------------------- night policy

/// What the night-policy controller reports. The renderer only displays it; a missing
/// or outdated report never claims darkness or wake.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct NightReport {
    pub version: u32,
    /// Local wall-clock bounds of scheduled darkness, e.g. "23:00" and "08:00".
    pub dark_from: String,
    pub dark_until: String,
    #[serde(flatten)]
    pub state: NightState,
    /// A known failure to apply the intended state to a device.
    #[serde(default)]
    pub failure: Option<Failure>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "mode", rename_all = "kebab-case")]
pub enum NightState {
    /// Both displays stay dark until explicitly resumed; wake is screen-only.
    Away {
        #[serde(default)]
        wake_until: Option<Timestamp>,
    },
    /// Screen on; scheduled darkness starts at `next_dark_at`.
    Day { next_dark_at: Timestamp },
    /// Scheduled darkness until `until`; `wake_until` while a screen-only wake runs.
    QuietHours {
        until: Timestamp,
        #[serde(default)]
        wake_until: Option<Timestamp>,
    },
    /// Manual bedtime until `until`; `wake_until` while a screen-only wake runs.
    Bedtime {
        until: Timestamp,
        #[serde(default)]
        wake_until: Option<Timestamp>,
    },
}
