apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/backup: enabled
    recurring-job-group.longhorn.io/snapshot: enabled
    recurring-job.longhorn.io/source: enabled
  name: gtnh-data
  namespace: gtnh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
