apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gtnh-rcon-data
  namespace: gtnh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
