apiVersion: v1
kind: Service
metadata:
  name: gtnh-public-nodeport
  namespace: gtnh
spec:
  ports:
    - name: minecraft
      nodePort: 30565
      port: 25565
      protocol: TCP
      targetPort: 25565
  selector:
    app: gtnh
  type: NodePort
