apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: gtnh-rcon
    tailscale.com/proxy-group: ingress
  name: gtnh-rcon-tailscale
  namespace: gtnh
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 4326
    - name: websocket
      port: 4327
      targetPort: 4327
  selector:
    app: gtnh-rcon
  type: LoadBalancer
