apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: longhorn
    tailscale.com/proxy-group: ingress
  name: longhorn-tailscale
  namespace: longhorn-system
spec:
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: longhorn-ui
  type: LoadBalancer
