apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/backup: enabled
    recurring-job-group.longhorn.io/snapshot: enabled
    recurring-job.longhorn.io/source: enabled
  name: crafty-servers
  namespace: crafty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: longhorn
