apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-import
  namespace: crafty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
