apiVersion: v1
kind: Service
metadata:
  name: crafty-minecraft-public-nodeport
  namespace: crafty
spec:
  ports:
    - name: minecraft
      nodePort: 30565
      port: 25565
      protocol: TCP
      targetPort: 25565
  selector:
    app: crafty
  type: NodePort
