#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Nothing here is written to disk: ENV_FILE is unused.
ENV_FILE=/dev/null

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"
# Stages commit explicit path lists; make sure nothing else is staged first.
git reset -q
REGISTRY=registry.tail84b6c.ts.net

# run "cmd..." echoes then runs a command inside the dev shell.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  nix develop -c "$@"
}

# commit_staged "message" commits the index if anything is staged (paths may
# already be in an earlier WIP commit), then pushes either way.
commit_staged() {
  if git diff --cached --quiet; then
    note "nothing new to commit for this stage (already committed)"
  else
    git commit -m "$1"
  fi
  git push
}

# wait_rollout NAMESPACE DEPLOYMENT... blocks until every deployment is rolled out.
wait_rollout() {
  local ns="$1"; shift
  for d in "$@"; do
    until run kubectl -n "$ns" rollout status "deploy/$d" --timeout=30s >/dev/null 2>&1; do sleep 10; done
  done
}

# watch_build NAMESPACE JOB waits for the PreSync build Job to appear, streams
# its log, and waits for it to complete.
watch_build() {
  local ns="$1" job="$2"
  say "Waiting for Argo CD to start ${job} (PreSync hook)…"
  until run kubectl -n "$ns" get job "$job" >/dev/null 2>&1; do sleep 5; done
  until run kubectl -n "$ns" logs "job/$job" --tail=1 >/dev/null 2>&1; do sleep 5; done
  run kubectl -n "$ns" logs -f "job/$job" || true
  run kubectl -n "$ns" wait --for=condition=complete "job/$job" --timeout=30m
}

banner "Self-hosted registry (zot) + in-cluster image builds"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Host: create the registry secrets"
say "The registry mounts 'zot-htpasswd' and the build Jobs mount a docker"
say "config.json; both come from sops via modules/nixos/kubernetes.nix, which"
say "needs a NixOS deploy."
note "Runs: just deploy  (nixos-rebuild switch --target-host homelab)"
if confirm "Deploy NixOS to homelab now?"; then
  just deploy
  say "Checking the secrets landed…"
  run kubectl -n registry get secret zot-htpasswd
  run kubectl -n changedetection get secret changedetection-registry-push
  run kubectl -n kodekamp get secret kodekamp-registry-push
else
  SKIPPED+=("just deploy (registry/build secrets will not exist until you do)")
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Git: deploy the registry"
say "Argo CD deploys from pushed main. This commits the registry, the secret"
say "plumbing, the flake changes, Glance and the dashboard — not the apps yet."
git status --short -- kubernetes/registry.nix kubernetes/dashboards/registry.json \
  modules/nixos/kubernetes.nix flake.nix flake.lock kubernetes/glance.nix secrets.yaml \
  manifests/homelab/registry manifests/homelab/glance manifests/homelab/apps/Application-registry.yaml
if confirm "Commit and push these files?"; then
  git add kubernetes/registry.nix kubernetes/dashboards/registry.json modules/nixos/kubernetes.nix \
    flake.nix flake.lock kubernetes/glance.nix secrets.yaml \
    manifests/homelab/registry manifests/homelab/glance manifests/homelab/apps/Application-registry.yaml
  commit_staged "registry: self-hosted zot on the tailnet"
  say "Waiting for Argo CD to roll out zot…"
  wait_rollout registry zot
  say "Checking HTTPS on the tailnet…"
  curl -fsS "https://${REGISTRY}/v2/" >/dev/null && say "${GREEN}✓${RESET} https://${REGISTRY}/v2/ answers"
  open_url "https://${REGISTRY}"
else
  SKIPPED+=("commit + push the registry (Argo CD has nothing to deploy)")
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Git: changedetection built in-cluster"
say "This commits the build helper, the changedetection image sources and the"
say "app change. Argo CD then runs the build-changedetection PreSync Job"
say "(apt + pip + Chromium download, several minutes) before rolling the pod."
warn "The two watches must be switched to the CloakBrowser fetcher afterwards."
if confirm "Commit and push?"; then
  git add images kubernetes/lib kubernetes/changedetection.nix manifests/homelab/changedetection \
    .github/workflows renovate.json5 docs/agents/adding-a-service.md scripts/setup-registry.sh
  commit_staged "changedetection: CloakBrowser fetcher image built in-cluster"
  watch_build changedetection build-changedetection
  wait_rollout changedetection changedetection
  say "${GREEN}✓${RESET} changedetection is running the in-cluster image"
else
  SKIPPED+=("commit + push the changedetection build (kubernetes/changedetection.nix)")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "changedetection: switch watches to CloakBrowser"
open_url "http://changedetection.tail84b6c.ts.net/settings#fetching"
step "Settings → Fetching → Default fetcher: 'CloakBrowser - Stealth Chromium'. Save."
step "Then open each watch → Edit → Request → Fetch method: 'System settings default'"
say "  (or pick CloakBrowser directly) and Save. Recheck one to confirm it fetches."
pause "Both watches fetch with CloakBrowser?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Git: KodeKamp built in-cluster"
say "This commits the KodeKamp change. Argo CD runs build-kodekamp (web + Rust"
say "code-runner, 10–20 minutes the first time) before rolling both Deployments"
say "from ghcr.io onto the registry. Renovate keeps the pinned commit fresh."
if confirm "Commit and push?"; then
  git add kubernetes/kodekamp.nix manifests/homelab/kodekamp
  commit_staged "kodekamp: build images in-cluster from the pinned commit"
  watch_build kodekamp build-kodekamp
  wait_rollout kodekamp kodekamp-web kodekamp-code-runner
  say "${GREEN}✓${RESET} KodeKamp is running from the registry"
else
  SKIPPED+=("commit + push kubernetes/kodekamp.nix + manifests/homelab/kodekamp")
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Wrap-up"
say "Optional: the old ghcr kodekamp-* packages can be deleted from GitHub"
say "Packages now that nothing pulls them. From here on, a Renovate bump to"
say "images/changedetection/* or the kodekamp flake input is all it takes:"
say "merge → nixidy regenerates → Argo builds → Argo rolls."
open_url "https://github.com/teevik?tab=packages"
pause

finish
