apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentopdf
  namespace: argocd
spec:
  destination:
    namespace: bentopdf
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/homelab/bentopdf
    repoURL: git@github.com:teevik/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
