apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-db
  namespace: dawarich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dawarich-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dawarich-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dawarich_production
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: dawarich-secrets
            - name: POSTGRES_USER
              value: postgres
          image: postgis/postgis:17-3.5-alpine@sha256:c75c8a8d4c0271f6bf788078e0ae8fa860a1c1a6904d2556c8b2a1b93753cd11
          name: postgis
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dawarich-db-data
