apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-redis-data
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
