apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: zot
  namespace: registry
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: zot
